
credits = '<a href="https://doteki.org"><img alt="Powered by dōteki" src="https://img.shields.io/badge/powered_by-d%C5%8Dteki-0?style=flat&labelColor=202b2d&color=5E936C" align="right"></a>'

[sections.blog]
plugin = "feed"
url = "https://idle-ti.me/atom.xml"
n = 10
show_date = true
separator = "•"
prepend_text = "### Latest blog posts\n\n"
append_text = "\n\nMore on [idle-ti.me](https://idle-ti.me)"

[sections.last_updated]
plugin = "current_date"
format = "%A, %d %B %Y, %H:%M%Z UTC"
prepend_text = "Last updated on "
append_text = "."
